In [2]:
import numpy as np

In [3]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

arr = arr*4
print(arr)

mean = np.mean(arr)
print(mean)

median = np.median(arr)
print(median)

std = np.std(arr)
print(std)

argmin = np.argmin(arr)
argmax = np.argmax(arr)

print(arr[argmin])
print(arr[argmax])

print(np.min(arr)) #These match the previous step
print(np.max(arr))

print(arr[arr > 20])

[ 80 108  36  48 124  68  16 200 156 140]
97.6
94.0
55.31582052180009
16
200
16
200
[ 80 108  36  48 124  68 200 156 140]


In [4]:
matrix = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]
arr2 = np.array(matrix)

print(np.shape(arr2))

print(arr2[:,2])

print(arr2[1,:])

arr2 = arr2 * 2
print(arr2)

for i in range(4):
    print(np.mean(arr2[:,i]))

print(np.mean(arr2))

for i in range(3):
    print(np.max(arr2[i,:]))
for i in range(4):
    print(np.min(arr2[:,i]))

arr2.flatten() #This made it a 1 x 12 matrix

min = np.argmin(arr2)
max = np.argmax(arr2)

np.unravel_index([max, min], (3, 4))

greater_than_15 = arr2[arr2 > 15]

np.sort(greater_than_15)
print(np.sort(greater_than_15))

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
12.666666666666666
30.666666666666668
33.333333333333336
15.333333333333334
23.0
34
42
38
10
24
28
6
[16 18 22 24 26 28 34 38 42]


In [5]:
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

def is_prime(i):
    if i < 2:
        return False
    for n in range(2, int(i**0.5) + 1):
        if i % n == 0:
            return False
    else:
        return True
        
def rows_with_primes(array):
    prime_rows = []
    for row in array:
        if any(is_prime(i) for i in row):
            prime_rows.append(row)
    return np.array(prime_rows)

print(rows_with_primes(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [12]:
checkerboard = np.array(range(64)).reshape(8,8)
checkerboard = checkerboard*0

checkerboard[1::2,1::2] = 1
checkerboard[::2,::2] = 1

reversed_checkerboard = np.abs(checkerboard - 1)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [28]:
universe = np.array(['galaxy', 'clusters'])

def expansion(arr, num):
    expanded_arr = []
    for word in arr:
        new_word = str()
        for char in word:
            new_word += char
            if char.isalpha:
                new_word += " " * num
        expanded_arr.append(new_word)
    return np.array(expanded_arr)

['g  a  l  a  x  y  ' 'c  l  u  s  t  e  r  s  ']
